trigger:
  - main

pool:
  name: Default
  agent: cicd-project-agent

jobs:

- job: BuildAndroid
  displayName: Build for Android

  pool:
    name: Default
    agent: cicd-project-agent

  steps:
  - task: DownloadSecureFile@1
    displayName: Get releaseKeyStore.jks
    name: releaseKeyStore
    inputs:
      secureFile: 'releaseKeyStore.jks'
  - pwsh: |
      Write-Host "##vso[task.setvariable variable=keyAlias;]$(androidKeystoreKeyAlias)"
      Write-Host "##vso[task.setvariable variable=keyPassword;]$(androidKeystoreKeyPassword)"
      Write-Host "##vso[task.setvariable variable=storeFile;]$(releaseKeyStore.secureFilePath)"
      Write-Host "##vso[task.setvariable variable=storePassword;]$(androidKeystorePassword)"
    displayName: "set keystore environment variables"
  - task: DownloadSecureFile@1
    displayName: Get google-services.json
    name: googleServicesJson
    inputs:
      secureFile: 'google-services.json'
  - pwsh: Move-Item $(googleServicesJson.secureFilePath) android/app/ -Force
    displayName: Override google-services.json
  - task: FlutterInstall@0
    displayName: Install Flutter
    inputs:
      channel: 'stable'
      version: 'latest'

  - script: flutter build web --$buildConfiguration
    displayName: 'Build Flutter Web'
    
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/build/web'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'
      replaceExistingArchive: true

  - powershell: |
      Expand-Archive -Path $(Build.ArtifactStagingDirectory)/webapp.zip -DestinationPath $(Build.ArtifactStagingDirectory)/unzipped_artifacts
    displayName: 'Unzip Artifacts'

  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws-flutter-deploy'
      regionName: 'us-east-1'
      bucketName: 'Flutter-Faizan'
      sourceFolder: '$(Build.ArtifactStagingDirectory)/unzipped_artifacts'
      globExpressions: '**'
      createBucket: true
