trigger:
  - main

pool:
  name: Default
  agent: cicd-project-agent

variables:
  buildConfiguration: 'release'

steps:
  - powershell: |
      Write-Host "Installing Flutter"
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      $env:PATH = "$($PWD.Path)\flutter\bin;$env:PATH"
      flutter --version
    displayName: 'Install Flutter'
    
  - script: flutter pub get
    displayName: 'Flutter Pub Get'

  - script: flutter build web --$buildConfiguration
    displayName: 'Build Flutter Web'
    
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/build/web'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'
      replaceExistingArchive: true

  - powershell: |
      Expand-Archive -Path $(Build.ArtifactStagingDirectory)/webapp.zip -DestinationPath $(Build.ArtifactStagingDirectory)/unzipped_artifacts
    displayName: 'Unzip Artifacts'

  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws-flutter-deploy'
      regionName: 'us-east-1'
      bucketName: 'Flutter-Faizan'
      sourceFolder: '$(Build.ArtifactStagingDirectory)/unzipped_artifacts'
      globExpressions: '**'
      createBucket: true
